{{- if .Values.forecaster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dfaas-forecaster
spec:
  type: ClusterIP
  selector:
    app: dfaas-forecaster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
{{- end }}
