{{- if .Values.forecaster.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfaas-forecaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfaas-forecaster
  template:
    metadata:
      labels:
        app: dfaas-forecaster
    spec:
      containers:
        - name: dfaas-forecaster
          image: {{ .Values.forecaster.image }}
          imagePullPolicy: {{ .Values.forecaster.imagePullPolicy }}
          ports:
            - containerPort: 8080
{{- end }}
